### ISSUE TITLE
构建的二进制文件 被 windows defender 认为含有木马

### ISSUE THREAD

**Issue by Zachary-Zhao** [unknown-marketwizards/lantube#1]
再次构建提示这个

go build lantube: open C:\Users\ASUS\AppData\Local\Temp\go-build513653794\b001\exe\a.out.exe: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

**Comment by themarketwizard** [comment]
go 用的是什么版本？是从官网下载的嘛？
