### ISSUE TITLE
我愿称佬为真神

### ISSUE THREAD

**Issue by orzchen** [unknown-marketwizards/lantube#10]
终于找到一个符合要求的了，其他的都太过于复杂。不过大佬，这个视频点播对于大视频的支持不是太好欸。

**Comment by orzchen** [comment]
提个小建议大佬，能否将文件目录和启动监听端口作为一个配置文件，这样可以多写一些目录。

**Comment by themarketwizard** [comment]
> 终于找到一个符合要求的了，其他的都太过于复杂。不过大佬，这个视频点播对于大视频的支持不是太好欸。

大视频怎么支持不太好？

**Comment by themarketwizard** [comment]
> 提个小建议大佬，能否将文件目录和启动监听端口作为一个配置文件，这样可以多写一些目录。

可以定义多个目录？

**Comment by orzchen** [comment]
1. 大视频那个问题是我格式问题
2. 希望可以定义多个目录
3. 还有就是移动端全屏支持不是很好欸
4.再次感谢大佬(*^_^*)

**Comment by themarketwizard** [comment]
189e9ab7af2939799c7f84cba02f646a789729cc
可以支持多个目录
