### ISSUE TITLE
最后运行时无法访问怎么办呀？

### ISSUE THREAD

**Issue by DrPhilip425** [unknown-marketwizards/lantube#6]
前面其他的操作都完成了的，就最后./lantube --addr 0.0.0.0:9000 video-sourse的时候打开https://0.0.0.0:9000显示的是：当前无法使用此页面0.0.0.0，当前无法处理此请求和HTTP ERROR 502，请问大佬该怎么解决呀

我GO的版本是1.21.0，用的是Windows11家庭版

**Comment by kcrazy** [comment]
用 127.0.0.1:9000 可以吗？

**Comment by DrPhilip425** [comment]
> 用 127.0.0.1:9000 可以吗？

谢谢大佬，127.0.0.1:9000是可以进入的

**Comment by kcrazy** [comment]
不客气
